networks:
  web-app-db-network-assign-one:
  api-cache-network-assign-one:
  express-network-assign-one:
 
volumes:
  moviedata: # persist MongoDB data across container restarts

services:
#CONTAINER 1
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api # uses image to create container on port 9000
    ports:
      - '9000:9000'
    networks:
      - api-cache-network-assign-one # movies api is on two networks so it can talk to redis without exposing it
      - web-app-db-network-assign-one
    depends_on:
      - database # db container must be created first as movies-api depends on it
      - caching
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017
      - ENABLE_WRITING_HANDLERS=false
      - RUST_BACKTRACE=full
      - REDIS_URI=redis://caching:6379
      # It took awhile to get  ^ this ^ working, caching relates to the service down below compose can route it using the name caching
      # the port number may not be needed especially if this changes but I am leaving it for now
      # ^^^ https://stackoverflow.com/questions/73780056/dns-resolver-failed-to-resolve-host-redis-failed-to-lookup-address-informati
      # ^^^ https://www.dragonflydb.io/error-solutions/redis-connection-error-111
  #CONTAINER 2
  database:
    container_name: mongo
    # ^^^ https://github.com/mongo-express/mongo-express/issues/437
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - web-app-db-network-assign-one
      - express-network-assign-one
    volumes: 
      - moviedata:/data/db 
  #CONTAINER 3
  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always # fixes MongoNetworkError caused by mongodb not being ready when mongo-express starts.
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://admin:secret@database:27017/
      # ^^^ https://github.com/mongo-express/mongo-express-docker/issues/67
      # ^^^ fixes "Could not connect to database using connectionString" error
    networks:
      - express-network-assign-one
    depends_on:
      - database
    profiles:
      - developer
  #CONTAINER 4
  caching:
    container_name: redis
    image: redis:alpine
    networks:
      - api-cache-network-assign-one # Only talk to movies api
  # CONTAINER 5: MongoDB Seeding
  # This spins up a container with the sole purpose of sending the JSON movie data from the host PC to the db
  # container at mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017
  fill-mongo:
    volumes:
      - ./seeding.json:/movies_via_seeding.json # data to be shared between the host and the container
    networks:
      - web-app-db-network-assign-one
    command:
    # https://www.mongodb.com/docs/database-tools/mongoimport/
    # https://stackoverflow.com/a/64372237
      mongoimport --authenticationDatabase=admin --db tmdb_movies
      --collection movies --drop --file /movies_via_seeding.json --jsonArray 
      mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017
    image: mongo:8.0-rc
